{
 "title": "Steam summary",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "games",
    "label": "Games",
    "query": "SELECT DISTINCT \"Name\" FROM steampartner.\"SteamGames\""
   }
  ]
 },
 "panels": [
  { "title": "Global data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Wishlists (Total)", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 1 } },
  { "title": "Wishlists (Current Period)", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 3, "y": 1 } },
  { "title": "Copies (Total)", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 6, "y": 1 } },
  { "title": "Copies (Current Period)", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 9, "y": 1 } },
  {
   "title": "Refund % (Total, Graph show trend)",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 1 }
  },
  { "title": "Followers", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 15, "y": 1 } },
  {
   "title": "Countries (copies sold, all time)",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"NetUnits\"), REPLACE(\"Country\", 'Russian Federation', 'Russia') as \"Country\" FROM steampartner.\"PackagesSales\" GROUP BY \"Country\""
    }
   ]
  },
  {
   "title": "$games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "repeat": "games",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  sum(\"Adds\") - sum(\"Deletes\") - SUM(\"PurchasesAndActivations\") - SUM(\"Gifts\")\nFROM steampartner.\"WishlistActions\"\nWHERE\n  \"Game\" = $games\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "repeat": "games",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  sum(\"Adds\") - sum(\"Deletes\") - SUM(\"PurchasesAndActivations\") - SUM(\"Gifts\")\nFROM steampartner.\"WishlistActions\"\nWHERE\n  $__timeFilter(\"Date\") AND\n  \"Game\" = $games\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "repeat": "games",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\", $__interval),\n  sum(\"NetUnits\")\nFROM steampartner.\"PackagesSales\"\nWHERE\n   \"Game\" = $games\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "repeat": "games",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\", $__interval),\n  sum(\"NetUnits\")\nFROM steampartner.\"PackagesSales\"\nWHERE\n  $__timeFilter(\"Date\") AND \n   \"Game\" = $games\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "repeat": "games",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  (SELECT 100.0 * SUM(\"ChargebackAndReturns\") / SUM(\"GrossUnits\") FROM steampartner.\"PackagesSales\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\"\nFROM steampartner.\"PackagesSales\" as currquery\nWHERE\n  \"Game\" = $games\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "repeat": "games",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" as time,\n  \"FollowerAmount\"\nFROM steampartner.\"SteamFollowers\"\nWHERE \"GameName\" = $games\nORDER BY 1\n  "
    }
   ]
  },
  { "title": "Wishlist status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$games - Wishlist status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "repeat": "games",
   "targets": [
    {
     "rawSql": "SELECT \r\n  \"Date\",\r\n  (SELECT SUM(\"Deletes\") FROM steampartner.\"WishlistActions\" b WHERE b.\"Date\" <= steampartner.\"WishlistActions\".\"Date\" AND b.\"Game\" = steampartner.\"WishlistActions\".\"Game\") as deleted,\r\n  (SELECT SUM(\"Adds\") - SUM(\"Deletes\") - SUM(\"PurchasesAndActivations\") FROM steampartner.\"WishlistActions\" b WHERE b.\"Date\" <= steampartner.\"WishlistActions\".\"Date\" AND b.\"Game\" = steampartner.\"WishlistActions\".\"Game\") as active, \r\n  (SELECT SUM(\"PurchasesAndActivations\") FROM steampartner.\"WishlistActions\" b WHERE b.\"Date\" <= steampartner.\"WishlistActions\".\"Date\" AND b.\"Game\" = steampartner.\"WishlistActions\".\"Game\") as purchased\r\nFROM steampartner.\"WishlistActions\" \r\nWHERE \"Game\" = $games AND\r\n  $__timeFilter(\"Date\")"
    }
   ]
  },
  {
   "title": "$games - Wishlist status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "games",
   "targets": [
    {
     "rawSql": "SELECT \r\n  \"Date\",\r\n  (100 * deleted / (deleted + active + purchased)) as deleted,\r\n  (100 * active / (deleted + active + purchased)) as active,\r\n  (100 * purchased / (deleted + active + purchased)) as purchased\r\nFROM (\r\n  SELECT \r\n    \"Date\",\r\n    (SELECT SUM(\"Deletes\") FROM steampartner.\"WishlistActions\" b WHERE b.\"Date\" <= steampartner.\"WishlistActions\".\"Date\" AND b.\"Game\" = steampartner.\"WishlistActions\".\"Game\") as deleted,\r\n    (SELECT SUM(\"Adds\") - SUM(\"Deletes\") - SUM(\"PurchasesAndActivations\") FROM steampartner.\"WishlistActions\" b WHERE b.\"Date\" <= steampartner.\"WishlistActions\".\"Date\" AND b.\"Game\" = steampartner.\"WishlistActions\".\"Game\") as active, \r\n    (SELECT SUM(\"PurchasesAndActivations\") FROM steampartner.\"WishlistActions\" b WHERE b.\"Date\" <= steampartner.\"WishlistActions\".\"Date\" AND b.\"Game\" = steampartner.\"WishlistActions\".\"Game\") as purchased\r\n  FROM steampartner.\"WishlistActions\" \r\n  WHERE \"Game\" = $games AND\r\n    $__timeFilter(\"Date\")\r\n) a\r\nWHERE (deleted + active + purchased) > 0"
    }
   ]
  },
  { "title": "Current period details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Active Wishlists (not deleted, not converted)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  (SELECT SUM(\"Adds\") - SUM(\"Deletes\") - SUM(\"PurchasesAndActivations\") - SUM(\"Gifts\") FROM steampartner.\"WishlistActions\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\n  \"Game\" as \"metric\"\nFROM steampartner.\"WishlistActions\" as currquery\nWHERE\n  $__timeFilter(currquery.\"Date\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"FollowerAmount\" as \"value\",\n  \"GameName\" as \"metric\"\nFROM steampartner.\"SteamFollowers\" as currquery\nWHERE\n  $__timeFilter(currquery.\"Date\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Copies sold | Net $ sold before taxes & steam cut",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"Date\" AS \"time\",\r\n  (SELECT SUM(\"NetUnits\") FROM steampartner.\"PackagesSales\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\r\n  CONCAT(\"Game\", ' (net units)') as \"metric\"\r\nFROM steampartner.\"PackagesSales\" as currquery\r\nWHERE\r\n  $__timeFilter(currquery.\"Date\")\r\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\r\n  \"Date\" AS \"time\",\r\n  (SELECT SUM(\"USDNetSteamSales\") FROM steampartner.\"PackagesSales\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\r\n  CONCAT(\"Game\", ' ($ net sale before taxes & steam cut)') as \"metric\"\r\nFROM steampartner.\"PackagesSales\" as currquery\r\nWHERE\r\n  $__timeFilter(currquery.\"Date\")\r\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\r\n  \"Date\" AS \"time\",\r\n  (SELECT SUM(\"USDGrossSteamSales\") FROM steampartner.\"PackagesSales\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\r\n  CONCAT(\"Game\", ' ($ gross)') as \"metric\"\r\nFROM steampartner.\"PackagesSales\" as currquery\r\nWHERE\r\n  $__timeFilter(currquery.\"Date\")\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stats from day 0 (public page or release date)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Active Wishlists (not deleted, not converted)",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"Date\" - (SELECT MIN(\"Date\") FROM steampartner.\"WishlistActions\" WHERE \"Game\" = currquery.\"Game\" AND \"Adds\" != 0)) AS \"day\",\n  (SELECT SUM(\"Adds\") - SUM(\"Deletes\") - SUM(\"PurchasesAndActivations\") FROM steampartner.\"WishlistActions\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\n  \"Game\" as metric\nFROM steampartner.\"WishlistActions\" as currquery\nWHERE \"Adds\" != 0 OR \"Deletes\" != 0\nORDER BY 1 ASC, 3 ASC"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"Date\" - (SELECT MIN(\"Date\") FROM steampartner.\"SteamFollowers\" WHERE \"GameName\" = currquery.\"GameName\")) AS \"day\",\n  \"FollowerAmount\" as \"value\",\n  \"GameName\" as metric\nFROM steampartner.\"SteamFollowers\" as currquery\nORDER BY 1 ASC, 3 ASC"
    }
   ]
  },
  {
   "title": "Copies sold",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  (\"Date\" - (SELECT MIN(\"Date\") FROM steampartner.\"PackagesSales\" WHERE \"Game\" = currquery.\"Game\" AND \"NetUnits\" != 0)) AS \"day\",\n  (SELECT SUM(\"NetUnits\") FROM steampartner.\"PackagesSales\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\n  \"Game\" as metric\nFROM steampartner.\"PackagesSales\" as currquery\nWHERE \"NetUnits\" != 0\nORDER BY 1 ASC, 3 ASC"
    }
   ]
  },
  {
   "title": "Other stats (refund, global revenues)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "% returns",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"Date\" AS \"time\",\r\n  (SELECT 100.0 * SUM(\"ChargebackAndReturns\") / SUM(\"GrossUnits\") FROM steampartner.\"PackagesSales\" as subquery WHERE subquery.\"Date\" <= currquery.\"Date\" and subquery.\"Game\" = currquery.\"Game\") as \"value\",\r\n  CONCAT(\"Game\", ' (% return)') as \"metric\"\r\nFROM steampartner.\"PackagesSales\" as currquery\r\nWHERE\r\n  $__timeFilter(currquery.\"Date\")\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Revenues - 1y",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  a.\"Date\" as \"time\",\r\n  SUM(b.\"USDGrossSteamSales\") AS \"Gross ($)\",\r\n  SUM(b.\"USDNetSteamSales\") AS \"Net ($)\"\r\nFROM (SELECT distinct \"Date\" FROM steampartner.\"PackagesSales\") a\r\nINNER JOIN steampartner.\"PackagesSales\" b ON b.\"Date\" BETWEEN (a.\"Date\" - interval '364 days') AND a.\"Date\"\r\nWHERE $__timeFilter(a.\"Date\") \r\nGROUP BY 1\r\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Copies - 1y",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  a.\"Date\" as \"time\",\r\n  SUM(b.\"GrossUnits\") AS \"Gross Units\",\r\n  SUM(b.\"NetUnits\") AS \"Net Units\"\r\nFROM (SELECT distinct \"Date\" FROM steampartner.\"PackagesSales\") a\r\nINNER JOIN steampartner.\"PackagesSales\" b ON b.\"Date\" BETWEEN (a.\"Date\" - interval '364 days') AND a.\"Date\"\r\nGROUP BY 1\r\nORDER BY 1 ASC"
    }
   ]
  }
 ]
}